model = "gpt-5.2-codex"
model_reasoning_effort = "high"
# full-auto mode
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

[model_providers.oneapi]
name = "lmrouter"
base_url = "https://one-api.ponte.top/v1"
env_key = "ONEAPI_API_KEY"
wire_api = "responses"

[model_providers.aicoding]
name = "aicoding"
base_url = "https://aicoding.2233.ai"
env_key = "AICODING_API_KEY"
wire_api = "responses"

[features]
apply_patch_freeform = true
shell_snapshot = true
skills = true
streamable_shell = true
unified_exec = true
web_search_request = true