model = "gpt-5.2-codex"
model_reasoning_effort = "medium"
# full-auto mode
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

[model_providers.aicoding]
name = "aicoding"
base_url = "https://aicoding.2233.ai"
env_key = "AICODING_API_KEY"
wire_api = "responses"

[model_providers.lmrouter]
name = "lmrouter"
base_url = "https://lmrouter.ponte.top/openai/v1"
env_key = "LMROUTER_API_KEY"
wire_api = "responses"

[features]
streamable_shell = true
web_search_request = true
unified_exec = true
shell_snapshot = true
